version: "4.0"

services:
  postgres:
    image: postgres:15
    container_name: "security"
    env_file:
      - .env
    environment:
      "POSTGRES_DB": ${POSTGRES_DB}
      "POSTGRES_USER": ${POSTGRES_USERNAME}
      "POSTGRES_PASSWORD": ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INTERNAL_PORT}"
